[package]
name = "M8r"
version = "0.1.0"
authors = ["Niklas Hansen <nha@3floor.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
