interface = "vcan0"
slot_size = 2
width = 480
height = 128

[colors]
primary = { r = 255, g = 255, b = 255 }
background = { r = 0, g = 0, b = 0 }

[[gauges]]
frame_id = 601
slot_id = 1
gauge = "Dial"
data_type = "F16"
title = "Boost"
unit = "bar"
min_value = -1.0
max_value = 2.0
indicators = [0.0]
digits = 2
point = { x = 0, y = 0 }
size = { width = 120, height = 128 }

[[gauges]]
frame_id = 602
slot_id = 1
gauge = "Dial"
data_type = "F16"
title = "Oil temp"
unit = "C"
min_value = 0.0
max_value = 150.0
indicators = [80.0]
digits = 0
point = { x = 128, y = 0 }
size = { width = 120, height = 128 }

[[gauges]]
frame_id = 603
slot_id = 1
gauge = "Dial"
data_type = "F16"
title = "Oil pres"
unit = "bar"
min_value = 0.0
max_value = 10.0
indicators = [2.0, 4.0, 6.0, 8.0]
digits = 1
point = { x = 256, y = 0 }
size = { width = 120, height = 128 }

[[gauges]]
frame_id = 604
slot_id = 1
gauge = "TextGauge"
data_type = "F16"
title = "H2O"
unit = "C"
digits = 0
point = { x = 384, y = 2 }
size = { width = 120, height = 10 }

[[gauges]]
frame_id = 605
slot_id = 1
gauge = "TextGauge"
data_type = "F16"
title = "IAT"
unit = "C"
digits = 0
point = { x = 384, y = 12 }
size = { width = 120, height = 10 }
