interface = "vcan0"
slot_size = 2

[[gauges]]
frame_id = 601
slot_id = 1
gauge = "Dial"
title = "Boost"
unit = "bar"
min_value = -1.0
max_value = 2.0
indicators = [0.0]
digits = 2
point = { x = 0, y = 0 }
size = { width = 64, height = 64 }

[[gauges]]
frame_id = 602
slot_id = 1
gauge = "Dial"
title = "Oil temp"
unit = "C"
min_value = 0.0
max_value = 150.0
indicators = [80.0]
digits = 0
point = { x = 64, y = 0 }
size = { width = 64, height = 64 }

[[gauges]]
frame_id = 603
slot_id = 1
gauge = "Dial"
title = "Oil pres"
unit = "bar"
min_value = 0.0
max_value = 10.0
indicators = [2.0, 4.0, 6.0, 8.0]
digits = 1
point = { x = 128, y = 0 }
size = { width = 64, height = 64 }

[[gauges]]
frame_id = 604
slot_id = 1
gauge = "TextGauge"
title = "H2O"
unit = "C"
digits = 0
point = { x = 192, y = 2 }
size = { width = 64, height = 10 }

[[gauges]]
frame_id = 605
slot_id = 1
gauge = "TextGauge"
title = "IAT"
unit = "C"
digits = 0
point = { x = 192, y = 12 }
size = { width = 64, height = 10 }
